services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: atonuser
      POSTGRES_PASSWORD: atonpassword
      POSTGRES_DB: atondb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Aton.career/Dockerfile
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=db;Port=5432;Database=atondb;Username=atonuser;Password=atonpassword
    ports:
      - "8080:8080"
    restart: always

volumes:
  pgdata: